import "./globals.css";
import "../assets/css/progress.css";
import ReduxProvider from "@/provider/ReduxProvider";
import FullScreenLoader from "@/components/Loader/FullScreenLoader";
import NextTopLoader from "nextjs-toploader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader color="#E60000" height={2} speed={200} />
      <ReduxProvider>
        {children}
          <FullScreenLoader/>
      </ReduxProvider>
      </body>
    </html>
  );
}
